Repository romi/romi-robots-docs, pull requests merged in 2021-03, with the labels that each got.

#48 GHA: Only deploy master branch
  .github/workflows/main.yml
Labels: bug

#44 New site version
  .github/workflows/main.yml
  custom_theme/partials/footer.html
  docs/about.md
  docs/data.md
  docs/documentation.md
  docs/index.md
  docs/research.md
  mkdocs.yml
  requirements.txt
Labels: documentation

#57 Refractoring segmentation
  docs/Scanner/explanations/segmentation.md
Labels: documentation, enhancement
